// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuração direta para testes (evite usar em produção)
const SUPABASE_URL = 'https://xiyvbnxkopggcveabhds.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeXZibnhrb3BnZ2N2ZWFiaGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMjk1NzksImV4cCI6MjA3NDgwNTU3OX0.fhg_dd5_YQDoVpPhcyPC_2cn83ZPDuxQLvq5HXzq8EE';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Configuração do Supabase ausente.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Desabilita confirmação de email para desenvolvimento
    detectSessionInUrl: true,
  }
});
